version: '2'

services:

  php:
    build:
      context: ./docker/php7-fpm
    image: laravel:php-fpm
    entrypoint:
      - php-fpm
    networks:
      - testmaker
    environment:
      DEBUG: 'true'
      DB_HOST: 'mysqlTestMaker'
      DB_DATABASE: 'testmaker'
      DB_USERNAME: 'testmaker'
      DB_PASSWORD: 'testmakerdb'
    volumes:
      - ./web/:/var/www/html:rw

  web:
    image: nginx:alpine
    container_name: nginx
    networks:
      - testmaker
    volumes_from:
      - php
    volumes:
      - ./docker/nginx/default:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  
networks:
  testmaker:
    external:
      name: testmaker