version: 2
jobs:
  build:
    docker:
       - image: marcostimm/laravel:1.1
    working_directory: ~/testmaker
    steps:
      - checkout
      - run: composer self-update
      - run: cd web && composer install -n --prefer-dist
      - run: php artisan migrate